//
//  EmailViewModel.swift
//  ExamenStefaniniOmar
//
//  Created by Omar Diaz on 29/06/23.
//

import Foundation

class EmailViewModel{
    static let shared = EmailViewModel()
    var globalData: [Message] =
    [
        Message(id: 1,
                emisor: "Bryan Perez",
                correoEmisor: "bperez@gmail.com",
                asunto: "Oficio a revisar",
                mensaje: "Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años, sino que tambien ingresó como texto de relleno en documentos electrónicos, quedando esencialmente igual al original. Fue popularizado en los 60s con la creación de las hojas , las cuales contenian pasajes de Lorem Ipsum, y más recientemente con software de autoedición, como por ejemplo Aldus PageMaker, el cual incluye versiones de Lorem Ipsum.",
                hora: "09:00 am",
                leido: true,
                destacado: true,
                spam: false),
        Message(id: 2,
                emisor: "Felipe Lopez",
                correoEmisor: "flopez@gmail.com",
                asunto: "Inicio de proyecto",
                mensaje: "Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años, sino que tambien ingresó como texto de relleno en documentos electrónicos, quedando esencialmente igual al original.",
                hora: "12:00 pm",
                leido: false,
                destacado: true,
                spam: false),
        Message(id: 3,
                emisor: "Antonio de Jesus",
                correoEmisor: "ajesus@gmail.com",
                asunto: "Nuevo articulo publicado",
                mensaje: "Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta)",
                hora: "05:15 pm",
                leido: false,
                destacado: false,
                spam: false),
        Message(id: 4,
                emisor: "Joaquin Vazquez",
                correoEmisor: "jvaquez@gmail.com",
                asunto: "Entrega de proyecto final",
                mensaje: "Desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años, sino que tambien ingresó como texto de relleno en documentos electrónicos, quedando esencialmente igual al original.",
                hora: "03:35 pm",
                leido: false,
                destacado: false,
                spam: true),
        Message(id: 5,
                emisor: "Victor Oropeza",
                correoEmisor: "voropeza@gmail.com",
                asunto: "Propuesta de proyecto",
                mensaje: "desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años, sino que tambien ingresó como texto de relleno en documentos electrónicos, quedando esencialmente igual al original.",
                hora: "08:00 am",
                leido: false,
                destacado: false,
                spam: false),
        Message(id: 6,
                emisor: "Juan Perez",
                correoEmisor: "jperez@gmail.com",
                asunto: "Tarea primer parcial",
                mensaje: "Este es un mensaje largo de un correo electronico de juan perez",
                hora: "10:00 am",
                leido: true,
                destacado: true,
                spam: false),
        Message(id: 7,
                emisor: "Lorena Diaz",
                correoEmisor: "ldiaz@gmail.com",
                asunto: "test",
                mensaje: "Desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años, sino que tambien ingresó como texto de relleno en documentos electrónicos, quedando esencialmente igual al original.",
                hora: "11:00 am",
                leido: false,
                destacado: true,
                spam: false),
        Message(id: 8,
                emisor: "Joseline Hernandez",
                correoEmisor: "jhernandez@gmail.com",
                asunto: "Cotizacion de productos",
                mensaje: "Este es un mensaje largo de un correo electronico de juan perez",
                hora: "02:00 pm",
                leido: false,
                destacado: false,
                spam: false),
        Message(id: 9,
                emisor: "Gabriel Avalos",
                correoEmisor: "gavalos@gmail.com",
                asunto: "Tarea primer parcial",
                mensaje: "Este es un mensaje largo de un correo electronico de juan perez",
                hora: "10:00 am",
                leido: false,
                destacado: false,
                spam: false),
        Message(id: 10,
                emisor: "Gabriela Davila",
                correoEmisor: "gdavila@gmail.com",
                asunto: "¡Documentacion solicitada!",
                mensaje: "Este es un mensaje largo de un correo electronico de juan perez",
                hora: "10:00 am",
                leido: false,
                destacado: false,
                spam: true),
        Message(id: 11,
                emisor: "Juan Perez",
                correoEmisor: "jperez@gmail.com",
                asunto: "Tarea primer parcial",
                mensaje: "Este es un mensaje largo de un correo electronico de juan perez",
                hora: "10:00 am",
                leido: false,
                destacado: false,
                spam: false),
        Message(id: 12,
                emisor: "Juan Perez",
                correoEmisor: "jperez@gmail.com",
                asunto: "Tarea primer parcial",
                mensaje: "Este es un mensaje largo de un correo electronico de juan perez",
                hora: "10:00 am",
                leido: true,
                destacado: true,
                spam: false),
        Message(id: 13,
                emisor: "Juan Perez",
                correoEmisor: "jperez@gmail.com",
                asunto: "Tarea primer parcial",
                mensaje: "Este es un mensaje largo de un correo electronico de juan perez",
                hora: "10:00 am",
                leido: false,
                destacado: true,
                spam: false),
        Message(id: 14,
                emisor: "Juan Perez",
                correoEmisor: "jperez@gmail.com",
                asunto: "Tarea primer parcial",
                mensaje: "Este es un mensaje largo de un correo electronico de juan perez",
                hora: "10:00 am",
                leido: false,
                destacado: false,
                spam: false),
        Message(id: 15,
                emisor: "Juan Perez",
                correoEmisor: "jperez@gmail.com",
                asunto: "Tarea primer parcial",
                mensaje: "Este es un mensaje largo de un correo electronico de juan perez",
                hora: "10:00 am",
                leido: false,
                destacado: false,
                spam: true),
        Message(id: 16,
                emisor: "Juan Perez",
                correoEmisor: "jperez@gmail.com",
                asunto: "Tarea primer parcial",
                mensaje: "Este es un mensaje largo de un correo electronico de juan perez",
                hora: "10:00 am",
                leido: false,
                destacado: false,
                spam: false),
        Message(id: 17,
                emisor: "Juan Perez",
                correoEmisor: "jperez@gmail.com",
                asunto: "Tarea primer parcial",
                mensaje: "Este es un mensaje largo de un correo electronico de juan perez",
                hora: "10:00 am",
                leido: true,
                destacado: true,
                spam: false),
        Message(id: 18,
                emisor: "Juan Perez",
                correoEmisor: "jperez@gmail.com",
                asunto: "Tarea primer parcial",
                mensaje: "Este es un mensaje largo de un correo electronico de juan perez",
                hora: "10:00 am",
                leido: false,
                destacado: true,
                spam: false),
        Message(id: 19,
                emisor: "Juan Perez",
                correoEmisor: "jperez@gmail.com",
                asunto: "Tarea primer parcial",
                mensaje: "Este es un mensaje largo de un correo electronico de juan perez",
                hora: "10:00 am",
                leido: false,
                destacado: false,
                spam: false),
        Message(id: 20,
                emisor: "Juan Perez",
                correoEmisor: "jperez@gmail.com",
                asunto: "Tarea primer parcial",
                mensaje: "Este es un mensaje largo de un correo electronico de juan perez",
                hora: "10:00 am",
                leido: false,
                destacado: false,
                spam: false),
        Message(id: 21,
                emisor: "Juan Perez",
                correoEmisor: "jperez@gmail.com",
                asunto: "Tarea primer parcial",
                mensaje: "Este es un mensaje largo de un correo electronico de juan perez",
                hora: "10:00 am",
                leido: false,
                destacado: false,
                spam: true),
        Message(id: 22,
                emisor: "Juan Perez",
                correoEmisor: "jperez@gmail.com",
                asunto: "Tarea primer parcial",
                mensaje: "Este es un mensaje largo de un correo electronico de juan perez",
                hora: "10:00 am",
                leido: false,
                destacado: false,
                spam: false),
    ]
    
    func getArray()->[Message]{
        return globalData
    }

    func addDataInArray(data : Message){
        globalData.append(data)
    }
    
}
