//
//  EmailViewModel.swift
//  ExamenStefaniniOmar
//
//  Created by Omar Diaz on 29/06/23.
//

import Foundation

class EmailViewModel{
    static let shared = EmailViewModel()
    var globalData: [Message] =
    [
        Message(id: 1,
                emisor: "Juan Perez 1",
                correoEmisor: "jperez@gmail.com",
                asunto: "Tarea primer parcial",
                mensaje: "Este es un mensaje largo de un correo electronico de juan perez",
                hora: "10:00 am",
                leido: true,
                destacado: true,
                spam: false),
        Message(id: 2,
                emisor: "Juan Perez 2",
                correoEmisor: "jperez@gmail.com",
                asunto: "Tarea primer parcial",
                mensaje: "Este es un mensaje largo de un correo electronico de juan perez",
                hora: "10:00 am",
                leido: false,
                destacado: true,
                spam: false),
        Message(id: 3,
                emisor: "Juan Perez 3",
                correoEmisor: "jperez@gmail.com",
                asunto: "Tarea primer parcial",
                mensaje: "Este es un mensaje largo de un correo electronico de juan perez",
                hora: "10:00 am",
                leido: false,
                destacado: false,
                spam: false),
        Message(id: 4,
                emisor: "Juan Perez 4",
                correoEmisor: "jperez@gmail.com",
                asunto: "Tarea primer parcial",
                mensaje: "Este es un mensaje largo de un correo electronico de juan perez",
                hora: "10:00 am",
                leido: false,
                destacado: false,
                spam: true),
        Message(id: 5,
                emisor: "Juan Perez 5",
                correoEmisor: "jperez@gmail.com",
                asunto: "Tarea primer parcial",
                mensaje: "Este es un mensaje largo de un correo electronico de juan perez",
                hora: "10:00 am",
                leido: false,
                destacado: false,
                spam: false),
        Message(id: 6,
                emisor: "Juan Perez",
                correoEmisor: "jperez@gmail.com",
                asunto: "Tarea primer parcial",
                mensaje: "Este es un mensaje largo de un correo electronico de juan perez",
                hora: "10:00 am",
                leido: true,
                destacado: true,
                spam: false),
        Message(id: 7,
                emisor: "Juan Perez",
                correoEmisor: "jperez@gmail.com",
                asunto: "Tarea primer parcial",
                mensaje: "Este es un mensaje largo de un correo electronico de juan perez",
                hora: "10:00 am",
                leido: false,
                destacado: true,
                spam: false),
        Message(id: 8,
                emisor: "Juan Perez",
                correoEmisor: "jperez@gmail.com",
                asunto: "Tarea primer parcial",
                mensaje: "Este es un mensaje largo de un correo electronico de juan perez",
                hora: "10:00 am",
                leido: false,
                destacado: false,
                spam: false),
        Message(id: 9,
                emisor: "Juan Perez",
                correoEmisor: "jperez@gmail.com",
                asunto: "Tarea primer parcial",
                mensaje: "Este es un mensaje largo de un correo electronico de juan perez",
                hora: "10:00 am",
                leido: false,
                destacado: false,
                spam: false),
        Message(id: 10,
                emisor: "Juan Perez",
                correoEmisor: "jperez@gmail.com",
                asunto: "Tarea primer parcial",
                mensaje: "Este es un mensaje largo de un correo electronico de juan perez",
                hora: "10:00 am",
                leido: false,
                destacado: false,
                spam: true),
        Message(id: 11,
                emisor: "Juan Perez",
                correoEmisor: "jperez@gmail.com",
                asunto: "Tarea primer parcial",
                mensaje: "Este es un mensaje largo de un correo electronico de juan perez",
                hora: "10:00 am",
                leido: false,
                destacado: false,
                spam: false),
        Message(id: 12,
                emisor: "Juan Perez",
                correoEmisor: "jperez@gmail.com",
                asunto: "Tarea primer parcial",
                mensaje: "Este es un mensaje largo de un correo electronico de juan perez",
                hora: "10:00 am",
                leido: true,
                destacado: true,
                spam: false),
        Message(id: 13,
                emisor: "Juan Perez",
                correoEmisor: "jperez@gmail.com",
                asunto: "Tarea primer parcial",
                mensaje: "Este es un mensaje largo de un correo electronico de juan perez",
                hora: "10:00 am",
                leido: false,
                destacado: true,
                spam: false),
        Message(id: 14,
                emisor: "Juan Perez",
                correoEmisor: "jperez@gmail.com",
                asunto: "Tarea primer parcial",
                mensaje: "Este es un mensaje largo de un correo electronico de juan perez",
                hora: "10:00 am",
                leido: false,
                destacado: false,
                spam: false),
        Message(id: 15,
                emisor: "Juan Perez",
                correoEmisor: "jperez@gmail.com",
                asunto: "Tarea primer parcial",
                mensaje: "Este es un mensaje largo de un correo electronico de juan perez",
                hora: "10:00 am",
                leido: false,
                destacado: false,
                spam: true),
        Message(id: 16,
                emisor: "Juan Perez",
                correoEmisor: "jperez@gmail.com",
                asunto: "Tarea primer parcial",
                mensaje: "Este es un mensaje largo de un correo electronico de juan perez",
                hora: "10:00 am",
                leido: false,
                destacado: false,
                spam: false),
        Message(id: 17,
                emisor: "Juan Perez",
                correoEmisor: "jperez@gmail.com",
                asunto: "Tarea primer parcial",
                mensaje: "Este es un mensaje largo de un correo electronico de juan perez",
                hora: "10:00 am",
                leido: true,
                destacado: true,
                spam: false),
        Message(id: 18,
                emisor: "Juan Perez",
                correoEmisor: "jperez@gmail.com",
                asunto: "Tarea primer parcial",
                mensaje: "Este es un mensaje largo de un correo electronico de juan perez",
                hora: "10:00 am",
                leido: false,
                destacado: true,
                spam: false),
        Message(id: 19,
                emisor: "Juan Perez",
                correoEmisor: "jperez@gmail.com",
                asunto: "Tarea primer parcial",
                mensaje: "Este es un mensaje largo de un correo electronico de juan perez",
                hora: "10:00 am",
                leido: false,
                destacado: false,
                spam: false),
        Message(id: 20,
                emisor: "Juan Perez",
                correoEmisor: "jperez@gmail.com",
                asunto: "Tarea primer parcial",
                mensaje: "Este es un mensaje largo de un correo electronico de juan perez",
                hora: "10:00 am",
                leido: false,
                destacado: false,
                spam: false),
        Message(id: 21,
                emisor: "Juan Perez",
                correoEmisor: "jperez@gmail.com",
                asunto: "Tarea primer parcial",
                mensaje: "Este es un mensaje largo de un correo electronico de juan perez",
                hora: "10:00 am",
                leido: false,
                destacado: false,
                spam: true),
        Message(id: 22,
                emisor: "Juan Perez",
                correoEmisor: "jperez@gmail.com",
                asunto: "Tarea primer parcial",
                mensaje: "Este es un mensaje largo de un correo electronico de juan perez",
                hora: "10:00 am",
                leido: false,
                destacado: false,
                spam: false),
    ]
    
    func getArray()->[Message]{
        return globalData
    }

    func addDataInArray(data : Message){
        globalData.append(data)
    }
    
}
